services:
  portfolio_dev_env:
    container_name: portfolio_develop
    image: node:18.3.0-alpine3.16
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["sh","-c","npm install && mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache && npm run start"]
  portfolio_prod_build:
    build:
      context: .
      dockerfile: ./Dockerfile_Prod_Build
    container_name: portfolio_prod_build
    ports:
      - 3000:80

