FROM node:18.3.0-alpine3.16 as builder
WORKDIR /app
COPY . .
COPY package.json /app/package.json
RUN npm install
# COPY ../portfolio_build /app
RUN npm run build
FROM nginx:alpine
COPY --from=builder /app/build usr/share/nginx/html

#CMD ["npm","run","start"]