name: pull-request-wrkflw

on:
  push:
    branches:
      - master

jobs:
  #seperate wrkflw
#  testing:
#    name: unit tests
#    runs-on: ubuntu-latest
#    steps:
#
  #seperate wrkflw
  build-docker-image:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: {secrets.SERVICE_ACCOUNT_KEY}
      - name: build & tag image
        run: |
              docker build -t portfolio -f Dockerfile_Prod_Build .
              docker tag portfolio us-east1-docker.pkg.dev/personal-portfolio-363722/portfolio/portfolio:1
      - name: push image to GCP
        run: docker push us-east1-docker.pkg.dev/personal-portfolio-363722/portfolio/portfolio:1
